In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("NBA_Player_Stats.csv")
del data['Rk']

In [4]:
data.head()

Player Pos  Age   Tm   G  GS    MP   FG   FGA    FG%   3P  \
0   Mahmoud Abdul-Rauf  PG   28  SAC  31   0  17.1  3.3   8.8  0.377  0.2   
1    Tariq Abdul-Wahad  SG   23  SAC  59  16  16.3  2.4   6.1  0.403  0.1   
2  Shareef Abdur-Rahim  SF   21  VAN  82  82  36.0  8.0  16.4  0.485  0.3   
3       Cory Alexander  PG   24  TOT  60  22  21.6  2.9   6.7  0.428  1.1   
4       Cory Alexander  PG   24  SAS  37   3  13.5  1.6   3.9  0.414  0.5   

   3PA    3P%   2P   2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB  TRB  AST  \
0  1.0  0.161  3.2   7.8  0.405  0.386  0.5  0.5  1.000  0.2  1.0  1.2  1.9   
1  0.3  0.211  2.4   5.7  0.414  0.409  1.4  2.1  0.672  0.7  1.2  2.0  0.9   
2  0.6  0.412  7.7  15.8  0.488  0.493  6.1  7.8  0.784  2.8  4.3  7.1  2.6   
3  2.9  0.375  1.8   3.7  0.469  0.510  1.3  1.7  0.784  0.3  2.2  2.4  3.5   
4  1.7  0.313  1.1   2.2  0.494  0.483  0.7  1.0  0.676  0.2  1.1  1.3  1.9   

   STL  BLK  TOV   PF   PTS       Year  
0  0.5  0.0  0.6  1.0   7.3  1997-1998  
1  0.6  0.2  1.1  1.4   6.4  1997-1998  
2  1.1  0.9  3.1  2.5  22.3  1997-1998  
3  1.2  0.2  1.9  1.6   8.1  1997-1998  
4  0.7  0.1  1.3  1.4   4.5  1997-1998

In [5]:
data

Player Pos  Age   Tm   G  GS    MP   FG   FGA    FG%   3P  \
0       Mahmoud Abdul-Rauf  PG   28  SAC  31   0  17.1  3.3   8.8  0.377  0.2   
1        Tariq Abdul-Wahad  SG   23  SAC  59  16  16.3  2.4   6.1  0.403  0.1   
2      Shareef Abdur-Rahim  SF   21  VAN  82  82  36.0  8.0  16.4  0.485  0.3   
3           Cory Alexander  PG   24  TOT  60  22  21.6  2.9   6.7  0.428  1.1   
4           Cory Alexander  PG   24  SAS  37   3  13.5  1.6   3.9  0.414  0.5   
...                    ...  ..  ...  ...  ..  ..   ...  ...   ...    ...  ...   
14568       Thaddeus Young  PF   33  TOR  26   0  18.3  2.6   5.5  0.465  0.7   
14569           Trae Young  PG   23  ATL  76  76  34.9  9.4  20.3  0.460  3.1   
14570       Omer Yurtseven   C   23  MIA  56  12  12.6  2.3   4.4  0.526  0.0   
14571          Cody Zeller   C   29  POR  27   0  13.1  1.9   3.3  0.567  0.0   
14572          Ivica Zubac   C   24  LAC  76  76  24.4  4.1   6.5  0.626  0.0   

       3PA    3P%   2P   2PA    2P%   eFG%   FT  FTA    FT%  ORB  DRB  TRB  \
0      1.0  0.161  3.2   7.8  0.405  0.386  0.5  0.5  1.000  0.2  1.0  1.2   
1      0.3  0.211  2.4   5.7  0.414  0.409  1.4  2.1  0.672  0.7  1.2  2.0   
2      0.6  0.412  7.7  15.8  0.488  0.493  6.1  7.8  0.784  2.8  4.3  7.1   
3      2.9  0.375  1.8   3.7  0.469  0.510  1.3  1.7  0.784  0.3  2.2  2.4   
4      1.7  0.313  1.1   2.2  0.494  0.483  0.7  1.0  0.676  0.2  1.1  1.3   
...    ...    ...  ...   ...    ...    ...  ...  ...    ...  ...  ...  ...   
14568  1.7  0.395  1.9   3.9  0.495  0.524  0.5  1.0  0.481  1.5  2.9  4.4   
14569  8.0  0.382  6.3  12.3  0.512  0.536  6.6  7.3  0.904  0.7  3.1  3.7   
14570  0.2  0.091  2.3   4.2  0.547  0.528  0.7  1.1  0.623  1.5  3.7  5.3   
14571  0.1  0.000  1.9   3.2  0.593  0.567  1.4  1.8  0.776  1.9  2.8  4.6   
14572  0.0    NaN  4.1   6.5  0.626  0.626  2.2  3.0  0.727  2.9  5.6  8.5   

       AST  STL  BLK  TOV   PF   PTS       Year  
0      1.9  0.5  0.0  0.6  1.0   7.3  1997-1998  
1      0.9  0.6  0.2  1.1  1.4   6.4  1997-1998  
2      2.6  1.1  0.9  3.1  2.5  22.3  1997-1998  
3      3.5  1.2  0.2  1.9  1.6   8.1  1997-1998  
4      1.9  0.7  0.1  1.3  1.4   4.5  1997-1998  
...    ...  ...  ...  ...  ...   ...        ...  
14568  1.7  1.2  0.4  0.8  1.7   6.3  2021-2022  
14569  9.7  0.9  0.1  4.0  1.7  28.4  2021-2022  
14570  0.9  0.3  0.4  0.7  1.5   5.3  2021-2022  
14571  0.8  0.3  0.2  0.7  2.1   5.2  2021-2022  
14572  1.6  0.5  1.0  1.5  2.7  10.3  2021-2022  

[14573 rows x 30 columns]

In [6]:
data.isnull().sum()

Player       0
Pos          0
Age          0
Tm           0
G            0
GS           0
MP           0
FG           0
FGA          0
FG%         88
3P           0
3PA          0
3P%       2198
2P           0
2PA          0
2P%        154
eFG%        88
FT           0
FTA          0
FT%        749
ORB          0
DRB          0
TRB          0
AST          0
STL          0
BLK          0
TOV          0
PF           0
PTS          0
Year         0
dtype: int64

# Label Encoding 

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
label_encoder_pos = LabelEncoder() 

In [9]:
data['Pos'] = label_encoder_pos.fit_transform(data['Pos']) 

In [10]:
label_encoder_tm = LabelEncoder() 

In [11]:
data['Tm'] = label_encoder_tm.fit_transform(data['Tm']) 

In [12]:
label_encoder_year = LabelEncoder() 

In [13]:
data['Year'] = label_encoder_tm.fit_transform(data['Year']) 

In [14]:
label_encoder_Player = LabelEncoder() 

In [15]:
data['Player_id'] = label_encoder_tm.fit_transform(data['Player']) 

In [16]:
data.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Player_id'],
      dtype='object')

# Creating new variables

In [17]:
data['PTS(t-1)'] = data.groupby('Player')['PTS'].shift(1)
data['G(t-1)'] = data.groupby('Player')['G'].shift(1)
#data['pts(t-2)'] = data.groupby('player_id')['pts'].shift(2)
data['AST(t-1)'] = data.groupby('Player')['AST'].shift(1)
#data['ast(t-2)'] = data.groupby('player_id')['ast'].shift(2)
data['TRB(t-1)'] = data.groupby('Player')['TRB'].shift(1)
#data['reb(t-2)'] = data.groupby('player_id')['reb'].shift(2)
data['FG(t-1)'] = data.groupby('Player')['FG'].shift(1)
data['FGA(t-1)'] = data.groupby('Player')['FGA'].shift(1)
data['3P(t-1)'] = data.groupby('Player')['3P'].shift(1)
data['3PA(t-1)'] = data.groupby('Player')['3PA'].shift(1)
data['2P(t-1)'] = data.groupby('Player')['2P'].shift(1)
data['2PA(t-1)'] = data.groupby('Player')['2PA'].shift(1)
data['FT(t-1)'] = data.groupby('Player')['FT'].shift(1)
data['FTA(t-1)'] = data.groupby('Player')['FTA'].shift(1)
data['DRB(t-1)'] = data.groupby('Player')['DRB'].shift(1)
data['ORB(t-1)'] = data.groupby('Player')['ORB'].shift(1)
data['TRB(t-1)'] = data.groupby('Player')['TRB'].shift(1)
data['STL(t-1)'] = data.groupby('Player')['STL'].shift(1)
data['BLK(t-1)'] = data.groupby('Player')['BLK'].shift(1)
data['TOV(t-1)'] = data.groupby('Player')['TOV'].shift(1)
data['PF(t-1)'] = data.groupby('Player')['PF'].shift(1)
data['G(t-1)'] = data.groupby('Player')['G'].shift(1)
data['MP(t-1)'] = data.groupby('Player')['MP'].shift(1)
data['Tm(t-1)'] = data.groupby('Player')['Tm'].shift(1)

In [18]:
data['team_change'] = np.nan

In [19]:
data['team_change'][data['Tm(t-1)'] == data['Tm']] = 0
data['team_change'][data['Tm(t-1)'] != data['Tm']] = 1

<ipython-input-19-0d6fc95754c2>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['team_change'][data['Tm(t-1)'] == data['Tm']] = 0
<ipython-input-19-0d6fc95754c2>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['team_change'][data['Tm(t-1)'] != data['Tm']] = 1


In [20]:
data.corr()

Pos       Age        Tm         G        GS        MP  \
Pos          1.000000 -0.051082  0.007768  0.010135 -0.005275  0.102714   
Age         -0.051082  1.000000  0.016749  0.035951  0.043532  0.093326   
Tm           0.007768  0.016749  1.000000  0.023289 -0.017810 -0.026068   
G            0.010135  0.035951  0.023289  1.000000  0.648261  0.623975   
GS          -0.005275  0.043532 -0.017810  0.648261  1.000000  0.794120   
MP           0.102714  0.093326 -0.026068  0.623975  0.794120  1.000000   
FG           0.073959  0.010772 -0.024386  0.531373  0.734992  0.895629   
FGA          0.150831  0.018025 -0.025177  0.508865  0.714500  0.901854   
FG%         -0.239691 -0.011968  0.001223  0.269591  0.216083  0.235876   
3P           0.389401  0.065222 -0.029085  0.296636  0.356668  0.531919   
3PA          0.411291  0.050970 -0.030588  0.278043  0.348973  0.538459   
3P%          0.259468  0.049405  0.003357  0.091369  0.073595  0.161377   
2P          -0.061164 -0.012096 -0.017026  0.498209  0.709396  0.828049   
2PA         -0.019179 -0.003194 -0.015763  0.486255  0.703586  0.839536   
2P%         -0.131075 -0.039081 -0.005343  0.215950  0.170010  0.197502   
eFG%        -0.064765  0.013886 -0.003285  0.286152  0.208137  0.271509   
FT           0.038129 -0.004907 -0.022279  0.425021  0.623736  0.753680   
FTA         -0.016119 -0.021919 -0.023981  0.424869  0.627075  0.750714   
FT%          0.238748  0.084633  0.006034  0.182271  0.159469  0.273349   
ORB         -0.448264 -0.019724 -0.010119  0.342314  0.440254  0.457966   
DRB         -0.265646  0.064084 -0.028526  0.476754  0.652642  0.741689   
TRB         -0.341060  0.039968 -0.023906  0.459453  0.619527  0.689925   
AST          0.160425  0.098077 -0.016352  0.363731  0.534624  0.677912   
STL          0.189507  0.043461 -0.013013  0.452040  0.592471  0.760200   
BLK         -0.385911 -0.019892 -0.024203  0.291432  0.391438  0.385371   
TOV          0.041537  0.017241 -0.018000  0.443324  0.650691  0.809594   
PF          -0.213445  0.062690 -0.016295  0.514781  0.571263  0.718361   
PTS          0.109427  0.014508 -0.026476  0.522562  0.724283  0.892639   
Year         0.048547 -0.119540 -0.020956 -0.094667 -0.064456 -0.041790   
Player_id    0.021097 -0.020941 -0.002130  0.005346  0.000984 -0.006781   
PTS(t-1)     0.123834  0.061979 -0.019009  0.412056  0.607450  0.744511   
G(t-1)       0.018229  0.085004  0.018018  0.526103  0.437460  0.491711   
AST(t-1)     0.178559  0.132131 -0.013443  0.278029  0.428834  0.549862   
TRB(t-1)    -0.362088  0.080004 -0.019266  0.352477  0.507252  0.520018   
FG(t-1)      0.085288  0.058417 -0.017526  0.419356  0.614564  0.742961   
FGA(t-1)     0.164775  0.063399 -0.018607  0.401916  0.594136  0.741809   
3P(t-1)      0.415175  0.096145 -0.017493  0.203069  0.258544  0.411899   
3PA(t-1)     0.433143  0.079590 -0.021129  0.189694  0.254689  0.417083   
2P(t-1)     -0.059097  0.030108 -0.012687  0.399683  0.600332  0.688414   
2PA(t-1)    -0.014401  0.037488 -0.012124  0.393317  0.594413  0.693158   
FT(t-1)      0.048551  0.032871 -0.016889  0.344347  0.540546  0.646034   
FTA(t-1)    -0.010203  0.016582 -0.017479  0.347495  0.547592  0.640623   
DRB(t-1)    -0.284536  0.106561 -0.021977  0.364979  0.533948  0.567856   
ORB(t-1)    -0.468385  0.009300 -0.010241  0.266405  0.363421  0.328123   
STL(t-1)     0.213109  0.082445 -0.007402  0.352007  0.486509  0.614776   
BLK(t-1)    -0.404655  0.004328 -0.022728  0.221175  0.331263  0.282885   
TOV(t-1)     0.053126  0.053409 -0.016520  0.351532  0.546837  0.663575   
PF(t-1)     -0.221756  0.099982 -0.011994  0.380557  0.449392  0.502778   
MP(t-1)      0.113554  0.150738 -0.018939  0.478366  0.637698  0.776416   
Tm(t-1)      0.000363  0.000166  0.348579 -0.111106 -0.070678 -0.059958   
team_change  0.030846 -0.013690  0.085188 -0.401306 -0.370871 -0.344848   

                   FG       FGA       FG%        3P       3PA       3P%  \
Pos          0.073959  0.150831 -0.239691 

In [21]:
data.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Player_id', 'PTS(t-1)', 'G(t-1)', 'AST(t-1)', 'TRB(t-1)', 'FG(t-1)',
       'FGA(t-1)', '3P(t-1)', '3PA(t-1)', '2P(t-1)', '2PA(t-1)', 'FT(t-1)',
       'FTA(t-1)', 'DRB(t-1)', 'ORB(t-1)', 'STL(t-1)', 'BLK(t-1)', 'TOV(t-1)',
       'PF(t-1)', 'MP(t-1)', 'Tm(t-1)', 'team_change'],
      dtype='object')

In [22]:
data.drop(columns = ['FG%', '3P%', '2P%', 'eFG%', 'FT%'], inplace = True)

In [23]:
data_final = data.dropna()

# Predicting points

In [24]:
#seperating independent and dependent variables
y = data_final['PTS']
X = data_final[['Player_id', 'PTS(t-1)', 'G(t-1)', 'AST(t-1)', 'TRB(t-1)', 'FG(t-1)',
       'FGA(t-1)', '3P(t-1)', '3PA(t-1)', '2P(t-1)', '2PA(t-1)', 'FT(t-1)',
       'FTA(t-1)', 'DRB(t-1)', 'ORB(t-1)', 'STL(t-1)', 'BLK(t-1)', 'TOV(t-1)',
       'PF(t-1)', 'MP(t-1)', 'Tm(t-1)', 'team_change', 'Pos', 'Age', 'Tm', 'Year']]

#importing train_test_split to create validation set
from sklearn.model_selection import train_test_split

#creating the train and validation set
X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state = 101, test_size=0.25)

In [25]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X_train_scaled = scale.fit_transform(X_train)
X_valid_scaled = scale.transform(X_valid)

# Gradient Boosting Algorithm

In [26]:
# how to import decision tree regressor
from sklearn.ensemble import GradientBoostingRegressor

#creating the decision tree function
dt_model = GradientBoostingRegressor()

In [27]:
#fitting the model
dt_model.fit(X_train, y_train)

GradientBoostingRegressor()

In [28]:
#checking the training score
dt_model.score(X_train, y_train)

0.7797870505209094

In [29]:
#checking the validation score
dt_model.score(X_valid, y_valid)

0.756217071773788

In [30]:
dt_model.feature_importances_

array([9.21837181e-04, 9.20866841e-01, 6.39227101e-03, 2.24712944e-03,
       4.27897119e-04, 2.35311387e-03, 8.27492884e-03, 1.32170333e-03,
       2.68463975e-03, 5.62403029e-04, 1.58733968e-03, 6.72645715e-03,
       1.40389517e-03, 1.59601353e-03, 8.64180736e-04, 3.13111442e-04,
       7.41843468e-04, 1.05808785e-03, 1.21179672e-03, 7.74476467e-04,
       5.61126564e-03, 1.17179388e-02, 1.61931932e-04, 1.78882286e-02,
       1.48544589e-03, 8.05222191e-04])

In [31]:
from sklearn.metrics import mean_absolute_error as mae
y_pred = dt_model.predict(X_valid)
mae(y_valid, y_pred)

2.2379044661369822

# SVM Algorithm

In [32]:
# how to import decision tree regressor
from sklearn.svm import SVR

#creating the decision tree function
dt_model = SVR()

#fitting the model
dt_model.fit(X_train_scaled, y_train)

SVR()

In [33]:
#checking the training score
dt_model.score(X_train_scaled, y_train)

0.7665100903394093

In [34]:
#checking the validation score
dt_model.score(X_valid_scaled, y_valid)

0.7452228183938263

In [35]:
from sklearn.metrics import mean_absolute_error as mae
y_pred = dt_model.predict(X_valid_scaled)
mae(y_valid, y_pred)

2.2533859787715484

# AdaBoost

In [36]:
# how to import decision tree regressor
from sklearn.ensemble import AdaBoostRegressor

#creating the decision tree function
dt_model = AdaBoostRegressor()

#fitting the model
dt_model.fit(X_train, y_train)

AdaBoostRegressor()

In [37]:
#checking the training score
dt_model.score(X_train, y_train)

0.6382419793625806

In [38]:
#checking the validation score
dt_model.score(X_valid, y_valid)

0.6235481422113436

In [39]:
dt_model.feature_importances_

array([0.00440862, 0.48795671, 0.02875904, 0.03732386, 0.00559319,
       0.01314547, 0.02859005, 0.01569495, 0.01331864, 0.00426212,
       0.01354595, 0.0756697 , 0.0159064 , 0.00863978, 0.01744305,
       0.00341251, 0.02105381, 0.01230137, 0.01648229, 0.01914696,
       0.05782933, 0.01165521, 0.01609901, 0.04434614, 0.01493361,
       0.01248224])

In [40]:
from sklearn.metrics import mean_absolute_error as mae
y_pred = dt_model.predict(X_valid)
mae(y_valid, y_pred)

3.05894199114196

# Predicting assist

In [41]:
#seperating independent and dependent variables
y = data_final['AST']
X = data_final[['Player_id', 'PTS(t-1)', 'G(t-1)', 'AST(t-1)', 'TRB(t-1)', 'FG(t-1)',
       'FGA(t-1)', '3P(t-1)', '3PA(t-1)', '2P(t-1)', '2PA(t-1)', 'FT(t-1)',
       'FTA(t-1)', 'DRB(t-1)', 'ORB(t-1)', 'STL(t-1)', 'BLK(t-1)', 'TOV(t-1)',
       'PF(t-1)', 'MP(t-1)', 'Tm(t-1)', 'team_change', 'Pos', 'Age', 'Tm', 'Year']]

#importing train_test_split to create validation set
from sklearn.model_selection import train_test_split

#creating the train and validation set
X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state = 101, test_size=0.25)

# Gradient Boosting Algorithm

In [42]:
# how to import decision tree regressor
from sklearn.ensemble import GradientBoostingRegressor

#creating the decision tree function
dt_model = GradientBoostingRegressor()

#fitting the model
dt_model.fit(X_train, y_train)

GradientBoostingRegressor()

In [43]:
#checking the training score
dt_model.score(X_train, y_train)

0.8113744390268253

In [44]:
#checking the validation score
dt_model.score(X_valid, y_valid)

0.8033039164273285

In [45]:
dt_model.feature_importances_

array([7.30588631e-04, 4.41240177e-03, 8.06898033e-03, 9.36843317e-01,
       1.54252570e-03, 4.41065698e-04, 1.78442608e-03, 6.00574942e-04,
       2.19177681e-03, 9.84844504e-04, 6.90069471e-04, 2.85115197e-03,
       3.66524212e-04, 1.08131463e-03, 5.57132157e-04, 2.57882168e-03,
       6.97068868e-04, 2.24768243e-03, 5.31464584e-04, 8.96114197e-04,
       1.53773269e-03, 7.50699944e-03, 1.44899697e-02, 4.24137888e-03,
       9.93599217e-04, 1.13247472e-03])

In [46]:
from sklearn.metrics import mean_absolute_error as mae
y_pred = dt_model.predict(X_valid)
mae(y_valid, y_pred)

0.5640199419665886

# Predicting rebounds

In [47]:
#seperating independent and dependent variables
y = data_final['TRB']
X = data_final[['Player_id', 'PTS(t-1)', 'G(t-1)', 'AST(t-1)', 'TRB(t-1)', 'FG(t-1)',
       'FGA(t-1)', '3P(t-1)', '3PA(t-1)', '2P(t-1)', '2PA(t-1)', 'FT(t-1)',
       'FTA(t-1)', 'DRB(t-1)', 'ORB(t-1)', 'STL(t-1)', 'BLK(t-1)', 'TOV(t-1)',
       'PF(t-1)', 'MP(t-1)', 'Tm(t-1)', 'team_change', 'Pos', 'Age', 'Tm', 'Year']]

In [48]:
#importing train_test_split to create validation set
from sklearn.model_selection import train_test_split

#creating the train and validation set
X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state = 101, test_size=0.25)

# Gradient Boosting Algorithm

In [49]:
# how to import decision tree regressor
from sklearn.ensemble import GradientBoostingRegressor

#creating the decision tree function
dt_model = GradientBoostingRegressor()

#fitting the model
dt_model.fit(X_train, y_train)

GradientBoostingRegressor()

In [50]:
#checking the training score
dt_model.score(X_train, y_train)

0.7593579414923667

In [51]:
#checking the validation score
dt_model.score(X_valid, y_valid)

0.7214227875300403

In [52]:
dt_model.feature_importances_

array([1.26831551e-03, 8.97803021e-04, 8.03191268e-03, 3.46246351e-04,
       8.95848064e-01, 8.79676558e-04, 6.36478637e-04, 1.60681716e-04,
       7.06146383e-04, 5.13315977e-03, 1.26049643e-03, 1.29848767e-03,
       4.23368986e-03, 1.05395901e-02, 1.52694124e-02, 4.08955263e-04,
       1.16359571e-02, 6.00832513e-04, 2.21994389e-03, 2.56433330e-03,
       4.54534512e-03, 6.79806264e-03, 1.07936281e-02, 1.24043536e-02,
       7.62857445e-04, 7.55570146e-04])

In [53]:
from sklearn.metrics import mean_absolute_error as mae
y_pred = dt_model.predict(X_valid)
mae(y_valid, y_pred)

0.9319500362662937

# Predicting games played

In [61]:
#seperating independent and dependent variables
y = data_final['G']
X = data_final[['Player_id', 'PTS(t-1)', 'G(t-1)', 'AST(t-1)', 'TRB(t-1)', 'FG(t-1)',
       'FGA(t-1)', '3P(t-1)', '3PA(t-1)', '2P(t-1)', '2PA(t-1)', 'FT(t-1)',
       'FTA(t-1)', 'DRB(t-1)', 'ORB(t-1)', 'STL(t-1)', 'BLK(t-1)', 'TOV(t-1)',
       'PF(t-1)', 'MP(t-1)', 'Tm(t-1)', 'Pos', 'Age', 'Tm', 'Year']]

In [62]:
#importing train_test_split to create validation set
from sklearn.model_selection import train_test_split

#creating the train and validation set
X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state = 101, test_size=0.25)

# Gradient Boosting Algorithm

In [63]:
# how to import decision tree regressor
from sklearn.ensemble import GradientBoostingRegressor

#creating the decision tree function
dt_model = GradientBoostingRegressor()

#fitting the model
dt_model.fit(X_train, y_train)

GradientBoostingRegressor()

In [64]:
#checking the training score
dt_model.score(X_train, y_train)

0.4799728833107083

In [65]:
#checking the validation score
dt_model.score(X_valid, y_valid)

0.4536177744231966

In [66]:
dt_model.feature_importances_

array([3.68746531e-03, 4.83518519e-02, 5.21139737e-01, 3.25069629e-03,
       4.92864398e-03, 8.20350034e-03, 2.21634698e-03, 9.64580312e-04,
       0.00000000e+00, 1.71314525e-02, 2.22781847e-03, 7.27925077e-03,
       9.74457867e-03, 6.25547403e-03, 4.93529605e-03, 3.12318724e-03,
       1.96808068e-03, 2.20452782e-03, 1.87878716e-03, 9.83289340e-02,
       1.34630952e-01, 3.05133719e-04, 1.48812704e-02, 2.24506629e-02,
       7.99117722e-02])

In [67]:
from sklearn.metrics import mean_absolute_error as mae
y_pred = dt_model.predict(X_valid)
mae(y_valid, y_pred)

15.358665533697708