In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
data_rookie = pd.read_csv("college_stats.csv")

In [3]:
data_rookie[data_rookie['Player'] == 'Mike Peplowski']

Player   Season          School     Conf Class     G    GS  \
4087  Mike Peplowski  1989-90  Michigan State  Big Ten    FR  28.0  23.0   
4088  Mike Peplowski  1990-91  Michigan State  Big Ten    SO  30.0  25.0   
4089  Mike Peplowski  1991-92  Michigan State  Big Ten    JR  30.0  29.0   
4090  Mike Peplowski  1992-93  Michigan State  Big Ten    SR  28.0  27.0   

        MP   FG  FGA    FG%   2P  2PA    2P%   3P  3PA  3P%   FT  FTA    FT%  \
4087  19.3  2.1  3.9  0.545  2.1  3.9  0.545  0.0  0.0  NaN  1.0  1.5  0.628   
4088  24.5  3.3  5.3  0.627  3.3  5.3  0.627  0.0  0.0  NaN  1.1  1.7  0.680   
4089  26.4  5.6  8.9  0.632  5.6  8.9  0.632  0.0  0.0  NaN  2.1  3.1  0.688   
4090  29.1  5.8  9.0  0.639  5.8  9.0  0.641  0.0  0.0  0.0  3.0  4.5  0.667   

      ORB  DRB   TRB  AST  STL  BLK  TOV   PF   PTS  Unnamed: 29    SOS  
4087  NaN  NaN   5.8  0.7  0.3  0.4  1.0  2.8   5.3          NaN   8.86  
4088  NaN  NaN   6.9  0.5  0.4  0.6  0.8  2.9   7.7          NaN   9.33  
4089  NaN  NaN   8.6  1.1  0.5  0.6  2.1  3.1  13.3          NaN  12.76  
4090  NaN  NaN  10.0  1.4  0.2  0.9  2.3  2.8  14.5          NaN   7.92

In [4]:
data_rookie['Player'].nunique()

1398

In [5]:
data_rookie['School'].unique()

array(['Duke', 'Gonzaga', 'Auburn', 'Iowa', 'Purdue', 'Arizona', 'Baylor',
       'Wisconsin', 'Santa Clara', 'Memphis', 'Kansas', 'Cincinnati',
       'LSU', 'Indiana State', 'Wake Forest', 'Ohio State', 'UNC',
       'Colorado State', 'Notre Dame', 'Milwaukee', 'Kentucky', 'UCLA',
       'Florida', 'Michigan', 'Arkansas', 'Michigan State', 'Tennessee',
       'Nebraska', 'Toledo', 'VCU', 'USC', 'Rhode Island', 'UConn',
       'Alabama', 'Colorado', 'Oklahoma State', 'Florida State',
       'Stanford', 'Oregon', 'Rice', 'Virginia', 'Texas', 'Arizona State',
       'Houston', 'Loyola (MD)', 'Villanova', 'Ohio', 'West Virginia',
       'Illinois', 'Utah State', 'Pepperdine', 'Western Kentucky',
       'Louisville', 'Creighton', 'Seton Hall', 'Maryland', 'Georgia',
       'Dayton', 'Iowa State', 'Vanderbilt', 'Washington',
       'Washington State', nan, 'San Diego State', 'TCU', 'Minnesota',
       'East Carolina', 'Syracuse', 'Mississippi State', 'Texas Tech',
       'Boise State', 'Co

In [6]:
data_rookie_last = data_rookie.groupby('Player').last().reset_index()

In [7]:
data_rookie_last

Player   Season          School      Conf Class     G    GS  \
0       A.J. Bramlett  1998-99         Arizona    Pac-10    SR  29.0  29.0   
1         A.J. Guyton  1999-00         Indiana   Big Ten    SR  29.0  29.0   
2        A.J. Hammons  2015-16          Purdue   Big Ten    SR  33.0  20.0   
3          A.J. Price  2008-09           UConn  Big East    SR  35.0  35.0   
4          AJ Griffin  2021-22            Duke       ACC    FR  39.0  25.0   
...               ...      ...             ...       ...   ...   ...   ...   
1393    Zach Randolph  2000-01  Michigan State   Big Ten    FR  33.0   8.0   
1394       Zeke Nnaji  2019-20         Arizona    Pac-12    FR  32.0  32.0   
1395     Zhaire Smith  2017-18      Texas Tech    Big 12    FR  37.0  21.0   
1396  Ziaire Williams  2020-21        Stanford    Pac-12    FR  20.0  14.0   
1397  Zion Williamson  2018-19            Duke       ACC    FR  33.0  33.0   

        MP   FG   FGA    FG%   2P   2PA    2P%   3P  3PA    3P%   FT  FTA  \
0     31.3  5.5  10.3  0.535  5.5  10.3  0.537  0.0  0.0  0.000  3.1  5.4   
1     34.3  7.0  15.3  0.459  4.6   9.4  0.485  2.5  5.9  0.419  3.1  3.9   
2     24.6  6.0  10.2  0.592  5.8   9.8  0.594  0.2  0.3  0.545  2.7  3.8   
3     31.8  4.9  11.9  0.408  2.5   6.1  0.413  2.3  5.8  0.402  2.7  3.7   
4     24.0  3.7   7.6  0.493  1.9   3.5  0.547  1.8  4.1  0.447  1.1  1.4   
...    ...  ...   ...    ...  ...   ...    ...  ...  ...    ...  ...  ...   
1393  19.8  4.2   7.1  0.587  4.2   7.1  0.590  0.0  0.0  0.000  2.4  3.8   
1394  30.7  5.6   9.8  0.570  5.4   9.3  0.586  0.2  0.5  0.294  4.8  6.3   
1395  28.4  4.2   7.5  0.556  3.7   6.4  0.574  0.5  1.1  0.450  2.5  3.4   
1396  27.9  3.8  10.2  0.374  2.7   6.2  0.427  1.2  4.0  0.291  2.0  2.5   
1397  30.0  9.0  13.2  0.680  8.2  11.0  0.747  0.7  2.2  0.338  3.9  6.2   

        FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS  Unnamed: 29    SOS  
0     0.576  NaN  NaN  9.4  1.2  0.8  1.3  2.0  3.2  14.2          NaN   8.35  
1     0.789  0.6  2.5  3.1  2.3  1.0  0.4  2.4  0.9  19.7          NaN  10.22  
2     0.709  2.3  5.8  8.2  1.1  0.3  2.5  2.0  2.4  15.0          NaN   7.46  
3     0.721  0.6  2.9  3.5  4.7  0.7  0.0  2.7  1.3  14.7          NaN   8.57  
4     0.792  0.8  3.2  3.9  1.0  0.5  0.6  0.6  1.1  10.4          NaN   7.26  
...     ...  ...  ...  ...  ...  ...  ...  ...  ...   ...          ...    ...  
1393  0.635  3.1  3.6  6.7  1.0  0.7  0.7  1.6  1.8  10.8          NaN   9.54  
1394  0.760  3.1  5.5  8.6  0.8  0.7  0.9  2.2  2.4  16.1          NaN   8.40  
1395  0.717  2.2  2.8  5.0  1.8  1.1  1.1  1.1  1.8  11.3          NaN   9.60  
1396  0.796  0.5  4.1  4.6  2.2  0.9  0.6  2.9  2.4  10.7          NaN  10.01  
1397  0.640  3.5  5.4  8.9  2.1  2.1  1.8  2.4  2.1  22.6          NaN  11.98  

[1398 rows x 31 columns]

In [8]:
data_rookie_last[data_rookie_last['Player'] == 'Mike Peplowski']

Player   Season          School     Conf Class     G    GS    MP  \
975  Mike Peplowski  1992-93  Michigan State  Big Ten    SR  28.0  27.0  29.1   

      FG  FGA    FG%   2P  2PA    2P%   3P  3PA  3P%   FT  FTA    FT%  ORB  \
975  5.8  9.0  0.639  5.8  9.0  0.641  0.0  0.0  0.0  3.0  4.5  0.667  NaN   

     DRB   TRB  AST  STL  BLK  TOV   PF   PTS  Unnamed: 29   SOS  
975  NaN  10.0  1.4  0.2  0.9  2.3  2.8  14.5          NaN  7.92

In [9]:
draft = pd.read_csv("Draft_picks_data.csv")

In [10]:
draft.head()

Player                    Team                Affiliation  Year  \
0  Victor Wembanyama       San Antonio Spurs  Metropolitans 92 (France)  2023   
1     Brandon Miller       Charlotte Hornets                    Alabama  2023   
2    Scoot Henderson  Portland Trail Blazers          Ignite (G League)  2023   
3      Amen Thompson         Houston Rockets             Overtime Elite  2023   
4     Ausar Thompson         Detroit Pistons             Overtime Elite  2023   

   Round Number  Round Pick  Overall Pick  
0             1           1             1  
1             1           2             2  
2             1           3             3  
3             1           4             4  
4             1           5             5

# Creating dataset

In [11]:
data = pd.read_csv("season_averages_3.csv")
del data['Unnamed: 0']

In [12]:
data

games_played  player_id  season    min    fgm     fga   fg3m   fg3a  \
0                12   46397639    1960  20:45  3.333   8.333  0.000  0.000   
1                39   46396616    1960  24:01  3.000   8.205  0.000  0.000   
2                18   46398147    1960  25:13  5.222  12.167  0.000  0.000   
3                39   46392456    1960  31:09  6.564  17.359  0.000  0.000   
4                33   46392455    1960  18:58  3.333   7.697  0.000  0.000   
...             ...        ...     ...    ...    ...     ...    ...    ...   
23067            18   56677832    2023   9:43  1.556   3.667  0.667  1.778   
23068            53   56677844    2023  26:50  2.981   6.698  1.000  2.736   
23069            14   56913527    2023   9:47  2.071   4.214  0.286  1.000   
23070             7   56677843    2023   9:51  1.571   2.571  0.143  0.571   
23071             5   56677838    2023   5:00  0.600   2.000  0.400  1.400   

         ftm    fta   oreb   dreb    reb    ast    stl    blk  turnover  \
0      0.750  1.167  0.000  0.000  6.750  0.417  0.000  0.000     0.000   
1      1.718  2.615  0.000  0.000  4.718  1.000  0.000  0.000     0.000   
2      3.611  4.167  0.000  0.000  4.667  1.389  0.000  0.000     0.000   
3      4.282  5.385  0.000  0.000  2.846  5.359  0.000  0.000     0.000   
4      2.697  3.242  0.000  0.000  6.030  0.182  0.000  0.000     0.000   
...      ...    ...    ...    ...    ...    ...    ...    ...       ...   
23067  0.333  0.389  0.444  1.111  1.556  1.111  0.500  0.333     0.556   
23068  1.377  1.962  0.887  3.189  4.075  1.755  0.849  0.774     1.491   
23069  2.357  3.000  0.714  1.357  2.071  0.286  0.214  0.000     0.143   
23070  0.857  0.857  0.857  1.000  1.857  0.857  0.000  0.143     0.429   
23071  0.200  0.400  0.400  0.800  1.200  0.200  0.000  0.000     0.200   

          pf     pts  fg_pct  fg3_pct  ft_pct first_name   last_name position  \
0      2.167   7.417   0.400    0.000   0.643       Mike      Farmer      NaN   
1      2.769   7.718   0.366    0.000   0.657         Si       Green      NaN   
2      2.222  14.056   0.429    0.000   0.867       Dave      Gambee      NaN   
3      2.615  17.436   0.378    0.000   0.795        Bob       Cousy      NaN   
4      2.818   9.364   0.433    0.000   0.832      Larry       Foust      NaN   
...      ...     ...     ...      ...     ...        ...         ...      ...   
23067  0.944   4.111   0.424    0.375   0.857     Jarace      Walker        F   
23068  2.170   8.340   0.445    0.366   0.702      Bilal   Coulibaly        G   
23069  0.571   6.786   0.492    0.286   0.786      Ricky  Council IV        G   
23070  0.714   4.143   0.611    0.250   1.000       Noah     Clowney        F   
23071  0.200   1.800   0.300    0.286   0.500       Kobe      Bufkin        G   

       height_feet  height_inches  weight_pounds  
0              NaN            NaN            NaN  
1              NaN            NaN            NaN  
2              NaN            NaN            NaN  
3              NaN            NaN            NaN  
4              NaN            NaN            NaN  
...            ...            ...            ...  
23067          NaN            NaN            NaN  
23068          NaN            NaN            NaN  
23069          NaN            NaN            NaN  
23070          NaN            NaN            NaN  
23071          NaN            NaN            NaN  

[23072 rows x 28 columns]

In [13]:
data['Player'] = data['first_name'] + ' ' + data['last_name']

In [14]:
data = data.groupby('player_id').first().reset_index()

In [15]:
merged_data = pd.merge(data, data_rookie_last, on='Player')

In [16]:
merged_data = pd.merge(merged_data, draft, on='Player')

In [17]:
merged_data.head()

player_id  games_played  season    min    fgm    fga   fg3m   fg3a    ftm  \
0          3            81    2013  14:48  1.148  2.284  0.000  0.000  0.975   
1          4            69    2017  19:49  2.522  4.928  0.000  0.101  1.870   
2          6            63    2006  21:50  3.830  7.600  0.000  0.030  1.320   
3          8            38    2018  10:56  1.763  4.684  0.842  2.605  1.184   
4          9            72    2017  20:00  3.250  5.514  0.069  0.208  1.583   

     fta   oreb   dreb    reb    ast    stl    blk  turnover     pf    pts  \
0  1.679  1.753  2.346  4.099  0.531  0.494  0.704     0.877  2.506  3.272   
1  2.594  1.710  3.812  5.522  1.464  0.464  0.594     0.957  2.000  6.913   
2  1.830  2.290  2.670  4.950  0.380  0.350  1.160     0.680  2.950  8.970   
3  1.579  0.079  0.526  0.605  0.658  0.158  0.158     0.868  1.237  5.553   
4  2.042  2.000  3.389  5.389  0.681  0.389  1.222     1.139  2.042  8.153   

   fg_pct  fg3_pct  ft_pct first_name last_name position  height_feet  \
0   0.503    0.000   0.581     Steven     Adams        C          7.0   
1   0.512    0.000   0.721        Bam   Adebayo      C-F          6.0   
2   0.503    0.000   0.722   LaMarcus  Aldridge        F          6.0   
3   0.376    0.323   0.750    Grayson     Allen        G          6.0   
4   0.589    0.333   0.776    Jarrett     Allen        C          6.0   

   height_inches  weight_pounds             Player   Season    School  \
0            0.0          265.0       Steven Adams  2012-13      Pitt   
1           10.0          255.0        Bam Adebayo  2016-17  Kentucky   
2           11.0          260.0  LaMarcus Aldridge  2005-06     Texas   
3            5.0          198.0      Grayson Allen  2017-18      Duke   
4           11.0          237.0      Jarrett Allen  2016-17     Texas   

       Conf Class     G    GS    MP   FG   FGA    FG%   2P   2PA    2P%   3P  \
0  Big East    FR  32.0  32.0  23.4  3.1   5.5  0.571  3.1   5.5  0.571  0.0   
1       SEC    FR  38.0  38.0  30.1  4.5   7.5  0.599  4.5   7.5  0.599  0.0   
2    Big 12    SO  37.0  37.0  33.7  5.9  10.4  0.569  5.9  10.4  0.569  0.0   
3       ACC    SR  37.0  37.0  35.6  4.9  11.7  0.418  2.1   4.2  0.503  2.8   
4    Big 12    FR  33.0  33.0  32.2  5.4   9.6  0.566  5.4   9.4  0.579  0.0   

   3PA   3P%   FT  FTA    FT%  ORB  DRB  TRB  AST  STL  BLK  TOV   PF   PTS  \
0  0.0   NaN  1.0  2.2  0.443  2.8  3.5  6.3  0.6  0.7  2.0  1.1  1.6   7.2   
1  0.0   NaN  4.1  6.2  0.653  3.1  4.9  8.0  0.8  0.7  1.5  1.7  2.6  13.0   
2  0.0   NaN  3.2  4.9  0.646  3.6  5.5  9.2  0.5  1.4  2.0  1.6  2.5  15.0   
3  7.5  0.37  2.9  3.4  0.850  0.5  2.8  3.3  4.6  1.7  0.1  2.1  2.1  15.5   
4  0.2  0.00  2.5  4.5  0.564  3.0  5.4  8.4  0.8  0.6  1.5  2.5  2.1  13.4   

   Unnamed: 29    SOS                   Team Affiliation  Year  Round Number  \
0          NaN   5.66  Oklahoma City Thunder  Pittsburgh  2013             1   
1          NaN  10.49             Miami Heat    Kentucky  2017             1   
2          NaN   6.99          Chicago Bulls       Texas  2006             1   
3          NaN   9.70              Utah Jazz        Duke  2018             1   
4          NaN  12.75          Brooklyn Nets       Texas  2017             1   

   Round Pick  Overall Pick  
0          12            12  
1          14            14  
2           2             2  
3          21            21  
4          22            22

In [18]:
merged_data.isnull().sum()

player_id       0
games_played    0
season          0
min             0
fgm             0
               ..
Affiliation     0
Year            0
Round Number    0
Round Pick      0
Overall Pick    0
Length: 65, dtype: int64

In [19]:
merged_data['3P%'].fillna(0, inplace = True)

In [20]:
del merged_data['Unnamed: 29']

In [21]:
del merged_data['ORB']
del merged_data['DRB']

In [22]:
merged_data['GS'].fillna(merged_data['G'], inplace = True)
merged_data['dreb'].fillna(merged_data['reb'] - merged_data['oreb'], inplace = True)

In [23]:
merged_data.isnull().sum()

player_id       0
games_played    0
season          0
min             0
fgm             0
               ..
Affiliation     0
Year            0
Round Number    0
Round Pick      0
Overall Pick    0
Length: 62, dtype: int64

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
# Creating an instance of LabelEncoder
label_encoder_Season = LabelEncoder()

# Encoding labels in the 'Category' column
merged_data['Season'] = label_encoder_Season.fit_transform(merged_data['Season'])

In [26]:
# Creating an instance of LabelEncoder
label_encoder_School = LabelEncoder()

# Encoding labels in the 'Category' column
merged_data['School'] = label_encoder_School.fit_transform(merged_data['School'])

In [27]:
# Creating an instance of LabelEncoder
label_encoder_Conf = LabelEncoder()

# Encoding labels in the 'Category' column
merged_data['Conf'] = label_encoder_Conf.fit_transform(merged_data['Conf'])

In [28]:
# Creating an instance of LabelEncoder
label_encoder_Class = LabelEncoder()

# Encoding labels in the 'Category' column
merged_data['Class'] = label_encoder_Class.fit_transform(merged_data['Class'])

In [29]:
merged_data.columns

Index(['player_id', 'games_played', 'season', 'min', 'fgm', 'fga', 'fg3m',
       'fg3a', 'ftm', 'fta', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk',
       'turnover', 'pf', 'pts', 'fg_pct', 'fg3_pct', 'ft_pct', 'first_name',
       'last_name', 'position', 'height_feet', 'height_inches',
       'weight_pounds', 'Player', 'Season', 'School', 'Conf', 'Class', 'G',
       'GS', 'MP', 'FG', 'FGA', 'FG%', '2P', '2PA', '2P%', '3P', '3PA', '3P%',
       'FT', 'FTA', 'FT%', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'SOS', 'Team', 'Affiliation', 'Year', 'Round Number', 'Round Pick',
       'Overall Pick'],
      dtype='object')

# Prediciting points

In [96]:
#seperating independent and dependent variables
y = merged_data['pts']
X = merged_data[['Season', 'School', 'Conf', 'Class', 'G',
       'GS', 'MP', 'FG', 'FGA', 'FG%', '2P', '2PA', '2P%', '3P', '3PA', '3P%',
       'FT', 'FTA', 'FT%', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'SOS','Overall Pick']]

In [133]:
#importing train_test_split to create validation set
from sklearn.model_selection import train_test_split

#creating the train and validation set
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25)

# Random Forest Algorithm

In [134]:
# how to import decision tree regressor
from sklearn.ensemble import GradientBoostingRegressor

#creating the decision tree function
dt_model = GradientBoostingRegressor(max_depth = 1)

#fitting the model
dt_model.fit(X_train, y_train)

GradientBoostingRegressor(max_depth=1)

In [135]:
#checking the training score
dt_model.score(X_train, y_train)

0.5119288501970283

In [136]:
#checking the validation score
dt_model.score(X_valid, y_valid)

0.45191752885971803

In [137]:
dt_model.feature_importances_

array([0.01369735, 0.        , 0.        , 0.00114916, 0.        ,
       0.        , 0.        , 0.01302682, 0.00134065, 0.        ,
       0.        , 0.        , 0.        , 0.00743166, 0.02792357,
       0.00195355, 0.        , 0.        , 0.00688454, 0.0112757 ,
       0.00432092, 0.02076399, 0.00124789, 0.        , 0.        ,
       0.02014078, 0.00793854, 0.86090488])

In [138]:
from sklearn.metrics import mean_absolute_error as mae
y_pred = dt_model.predict(X_valid)
mae(y_valid, y_pred)

2.4978518274376937

# AdaBoost

In [65]:
# how to import decision tree regressor
from sklearn.ensemble import AdaBoostRegressor

#creating the decision tree function
dt_model = AdaBoostRegressor()

#fitting the model
dt_model.fit(X_train, y_train)

AdaBoostRegressor()

In [66]:
#checking the training score
dt_model.score(X_train, y_train)

0.507887537240429

In [67]:
#checking the validation score
dt_model.score(X_valid, y_valid)

0.3273969109922792

In [68]:
dt_model.feature_importances_

array([0.00158829, 0.00514036, 0.00858189, 0.02594546, 0.00738537,
       0.00394497, 0.02112025, 0.02974898, 0.01129839, 0.03021078,
       0.00376118, 0.00413519, 0.01331207, 0.01459634, 0.0277599 ,
       0.00331756, 0.01899679, 0.01056788, 0.00935993, 0.00674488,
       0.00732557, 0.01962312, 0.00796034, 0.0317585 , 0.        ,
       0.06365049, 0.047018  , 0.56514748])

In [69]:
from sklearn.metrics import mean_absolute_error as mae
y_pred = dt_model.predict(X_valid)
mae(y_valid, y_pred)

2.776111450363722

# Prediciting assists

In [139]:
#seperating independent and dependent variables
y = merged_data['ast']
X = merged_data[['Season', 'School', 'Conf', 'Class', 'G',
       'GS', 'MP', 'FG', 'FGA', 'FG%', '2P', '2PA', '2P%', '3P', '3PA', '3P%',
       'FT', 'FTA', 'FT%', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'SOS','Overall Pick']]

In [140]:
#importing train_test_split to create validation set
from sklearn.model_selection import train_test_split

#creating the train and validation set
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25)

# Random Forest Algorithm

In [174]:
# how to import decision tree regressor
from sklearn.ensemble import RandomForestRegressor

#creating the decision tree function
dt_model = RandomForestRegressor(max_depth = 3)

#fitting the model
dt_model.fit(X_train, y_train)

RandomForestRegressor(max_depth=3)

In [175]:
#checking the training score
dt_model.score(X_train, y_train)

0.6333766735641987

In [176]:
#checking the validation score
dt_model.score(X_valid, y_valid)

0.5337568624417495

In [177]:
dt_model.feature_importances_

array([0.00000000e+00, 1.68681334e-03, 3.00752229e-04, 1.37790343e-03,
       2.52553212e-03, 0.00000000e+00, 8.56165275e-03, 1.91944149e-04,
       1.51711129e-03, 6.12904445e-03, 0.00000000e+00, 9.59924293e-04,
       1.32269982e-02, 7.75259246e-03, 1.96570109e-02, 2.44752678e-03,
       4.08633551e-04, 1.15137456e-03, 9.70735776e-04, 5.76453590e-03,
       5.32932781e-01, 1.92461784e-02, 4.96369221e-03, 6.34672809e-03,
       5.57478115e-03, 0.00000000e+00, 8.63572892e-04, 3.55442180e-01])

In [178]:
from sklearn.metrics import mean_absolute_error as mae
y_pred = dt_model.predict(X_valid)
mae(y_valid, y_pred)

0.5617119329474871

# Prediciting rebounds

In [191]:
#seperating independent and dependent variables
y = merged_data['reb']
X = merged_data[['Season', 'School', 'Conf', 'Class', 'G',
       'GS', 'MP', 'FG', 'FGA', 'FG%', '2P', '2PA', '2P%', '3P', '3PA', '3P%',
       'FT', 'FTA', 'FT%', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'SOS','Overall Pick']]

In [192]:
#importing train_test_split to create validation set
from sklearn.model_selection import train_test_split

#creating the train and validation set
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25)

# Random Forest Algorithm

In [193]:
# how to import decision tree regressor
from sklearn.ensemble import RandomForestRegressor

#creating the decision tree function
dt_model = RandomForestRegressor(max_depth = 4)

#fitting the model
dt_model.fit(X_train, y_train)

RandomForestRegressor(max_depth=4)

In [194]:
#checking the training score
dt_model.score(X_train, y_train)

0.5398075034934995

In [195]:
#checking the validation score
dt_model.score(X_valid, y_valid)

0.49139537580839787

In [196]:
dt_model.feature_importances_

array([0.00674594, 0.00319056, 0.00452357, 0.00363124, 0.00320941,
       0.00596703, 0.01859563, 0.00358049, 0.0038628 , 0.06196858,
       0.01020529, 0.00940784, 0.02326855, 0.01070067, 0.02594925,
       0.0080217 , 0.00439183, 0.00543797, 0.01486855, 0.18828748,
       0.00627165, 0.00475869, 0.02743976, 0.00224884, 0.00673178,
       0.00908839, 0.00524958, 0.52239694])

In [197]:
from sklearn.metrics import mean_absolute_error as mae
y_pred = dt_model.predict(X_valid)
mae(y_valid, y_pred)

1.0540725158152993

# Prediciting steals

In [221]:
#seperating independent and dependent variables
y = merged_data['stl']
X = merged_data[['Season', 'School', 'Conf', 'Class', 'G',
       'GS', 'MP', 'FG', 'FGA', 'FG%', '2P', '2PA', '2P%', '3P', '3PA', '3P%',
       'FT', 'FTA', 'FT%', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'SOS','Overall Pick']]

In [222]:
#importing train_test_split to create validation set
from sklearn.model_selection import train_test_split

#creating the train and validation set
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25)

# Random Forest Algorithm

In [223]:
# how to import decision tree regressor
from sklearn.ensemble import RandomForestRegressor

#creating the decision tree function
dt_model = RandomForestRegressor(max_depth = 4)

#fitting the model
dt_model.fit(X_train, y_train)

RandomForestRegressor(max_depth=4)

In [224]:
#checking the training score
dt_model.score(X_train, y_train)

0.5432174723162759

In [225]:
#checking the validation score
dt_model.score(X_valid, y_valid)

0.36932154111232596

In [226]:
dt_model.feature_importances_

array([0.00412999, 0.00791265, 0.00458499, 0.00304318, 0.0051169 ,
       0.00345014, 0.01535175, 0.00808622, 0.01019519, 0.0064418 ,
       0.00573285, 0.01145331, 0.01182899, 0.00570689, 0.00825454,
       0.00731008, 0.00542622, 0.00586514, 0.00498418, 0.00451334,
       0.03756669, 0.39468764, 0.01290336, 0.00550134, 0.00894379,
       0.00615119, 0.01154348, 0.38331416])

In [227]:
from sklearn.metrics import mean_absolute_error as mae
y_pred = dt_model.predict(X_valid)
mae(y_valid, y_pred)

0.22477670258136

# Prediciting blocks

In [228]:
#seperating independent and dependent variables
y = merged_data['blk']
X = merged_data[['Season', 'School', 'Conf', 'Class', 'G',
       'GS', 'MP', 'FG', 'FGA', 'FG%', '2P', '2PA', '2P%', '3P', '3PA', '3P%',
       'FT', 'FTA', 'FT%', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'SOS','Overall Pick']]

In [229]:
#importing train_test_split to create validation set
from sklearn.model_selection import train_test_split

#creating the train and validation set
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.25)

# Random Forest Algorithm

In [230]:
# how to import decision tree regressor
from sklearn.ensemble import RandomForestRegressor

#creating the decision tree function
dt_model = RandomForestRegressor(max_depth = 2)

#fitting the model
dt_model.fit(X_train, y_train)

RandomForestRegressor(max_depth=2)

In [231]:
#checking the training score
dt_model.score(X_train, y_train)

0.49626896907911966

In [232]:
#checking the validation score
dt_model.score(X_valid, y_valid)

0.5076988634450896

In [233]:
dt_model.feature_importances_

array([0.01224206, 0.        , 0.00182354, 0.00182321, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.00792223, 0.        , 0.        ,
       0.00135626, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.80093258, 0.        , 0.00145291,
       0.        , 0.        , 0.17244721])

In [234]:
from sklearn.metrics import mean_absolute_error as mae
y_pred = dt_model.predict(X_valid)
mae(y_valid, y_pred)

0.17593325264539908